# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: 
  adapter: postgresql
  database: jetcrawler
  username: jetdeck
  password: jetdeck 
  host: localhost 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jetdeck
  username: jetdeck 
  password: Gulfstream1
  host: jetdb1.c4ussfstr7ky.us-east-1.rds.amazonaws.com
  port: 3306


